'use client';

import { motion } from 'framer-motion';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { BoardTask } from './KanbanBoard';

export function DashboardAnalytics({ tasks }: { tasks: BoardTask[] }) {
  const completed = tasks.filter((task) => task.is_completed).length;
  const overdue = tasks.filter((task) => task.due_date && !task.is_completed && new Date(task.due_date) < new Date()).length;
  const statusData = [{ name: 'To Do', value: tasks.filter((task) => !task.status && !task.is_completed || task.status === 'todo').length }, { name: 'Progress', value: tasks.filter((task) => task.status === 'in_progress').length }, { name: 'Review', value: tasks.filter((task) => task.status === 'review').length }, { name: 'Done', value: completed }];
  const trend = [{ day: 'Mon', completed: Math.max(0, completed - 3) }, { day: 'Tue', completed: Math.max(0, completed - 2) }, { day: 'Wed', completed: Math.max(0, completed - 1) }, { day: 'Thu', completed }, { day: 'Fri', completed: completed + 1 }];
  const stats = [['Total tasks', tasks.length, 'analytics-purple'], ['Completed', completed, 'analytics-green'], ['Pending', tasks.length - completed, 'analytics-blue'], ['Overdue', overdue, 'analytics-orange']];
  return <section className="analytics-section"><div className="analytics-header"><div><span className="eyebrow">Your momentum</span><h2>Advanced overview</h2></div><span className="data-source">Live from task API</span></div><div className="stats-grid">{stats.map(([label, value, className]) => <motion.div key={String(label)} className={`stat-card ${className}`} whileHover={{ y: -4 }}><span>{label}</span><strong>{value}</strong><small>{label === 'Completed' ? `${tasks.length ? Math.round((Number(value) / tasks.length) * 100) : 0}% of all tasks` : 'Updated just now'}</small></motion.div>)}</div><div className="charts-grid"><div className="chart-card"><div className="chart-heading"><div><span>Completion trend</span><h3>Weekly output</h3></div><span className="chart-legend">● Completed</span></div><ResponsiveContainer width="100%" height={220}><AreaChart data={trend}><defs><linearGradient id="completionFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--accent)" stopOpacity={.45} /><stop offset="100%" stopColor="var(--accent)" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="var(--line)" vertical={false} /><XAxis dataKey="day" stroke="var(--muted)" fontSize={11} /><YAxis stroke="var(--muted)" fontSize={11} allowDecimals={false} /><Tooltip contentStyle={{ background: 'var(--surface-solid)', border: '1px solid var(--line)', borderRadius: 8 }} /><Area type="monotone" dataKey="completed" stroke="var(--accent)" fill="url(#completionFill)" strokeWidth={3} /></AreaChart></ResponsiveContainer></div><div className="chart-card"><div className="chart-heading"><div><span>Workload</span><h3>Tasks by status</h3></div></div><ResponsiveContainer width="100%" height={220}><BarChart data={statusData}><CartesianGrid stroke="var(--line)" vertical={false} /><XAxis dataKey="name" stroke="var(--muted)" fontSize={10} /><YAxis stroke="var(--muted)" fontSize={11} allowDecimals={false} /><Tooltip contentStyle={{ background: 'var(--surface-solid)', border: '1px solid var(--line)', borderRadius: 8 }} /><Bar dataKey="value" fill="var(--accent)" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></div></section>;
}
