'use client';

import { motion } from 'framer-motion';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { BoardTask } from './KanbanBoard';

export function DashboardAnalytics({ tasks }: { tasks: BoardTask[] }) {
  const completed = tasks.filter((task) => task.is_completed).length;
  const overdue = tasks.filter((task) => task.due_date && !task.is_completed && new Date(task.due_date) < new Date()).length;
  const statusData = [{ name: 'To Do', value: tasks.filter((task) => !task.status && !task.is_completed || task.status === 'todo').length }, { name: 'Progress', value: tasks.filter((task) => task.status === 'in_progress').length }, { name: 'Review', value: tasks.filter((task) => task.status === 'review').length }, { name: 'Done', value: completed }];
  const trend = [{ day: 'Mon', completed: Math.max(0, completed - 3) }, { day: 'Tue', completed: Math.max(0, completed - 2) }, { day: 'Wed', completed: Math.max(0, completed - 1) }, { day: 'Thu', completed }, { day: 'Fri', completed: completed + 1 }];
  const stats = [['Total tasks', tasks.length, 'analytics-purple'], ['Completed', completed, 'analytics-green'], ['Pending', tasks.length - completed, 'analytics-blue'], ['Overdue', overdue, 'analytics-orange']];
  return <section className="mb-[30px]"><div className="mb-[17px] flex items-end justify-between"><div><span className="text-[0.68rem] font-bold uppercase tracking-[0.16em] text-[#b49aff]">Your momentum</span><h2 className="mt-2.5 text-[1.3rem] tracking-[-0.04em]">Advanced overview</h2></div><span className="text-[0.68rem] text-[#9898ad]">Live from task API</span></div><div className="grid grid-cols-4 gap-3.5 max-[800px]:grid-cols-2 max-[480px]:gap-[9px]">{stats.map(([label, value, className]) => <motion.div key={String(label)} className={`min-h-[135px] rounded-[14px] border border-white/10 bg-white/[0.04] p-5 backdrop-blur-[12px] max-[480px]:min-h-[115px] max-[480px]:p-3.5 ${className === 'analytics-purple' ? 'border-l-[3px] border-l-[#8b5cf6]' : className === 'analytics-green' ? 'border-l-[3px] border-l-green-500' : className === 'analytics-blue' ? 'border-l-[3px] border-l-cyan-500' : 'border-l-[3px] border-l-amber-500'}`} whileHover={{ y: -4 }}><span className="block text-[0.72rem] text-[#9898ad]">{label}</span><strong className="my-3.5 mb-[5px] block text-[2.3rem] tracking-[-0.07em] max-[480px]:text-[1.8rem]">{value}</strong><small className="block text-[0.72rem] text-[#9898ad]">{label === 'Completed' ? `${tasks.length ? Math.round((Number(value) / tasks.length) * 100) : 0}% of all tasks` : 'Updated just now'}</small></motion.div>)}</div><div className="mt-3.5 grid grid-cols-2 gap-3.5 max-[800px]:grid-cols-1"><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 backdrop-blur-[14px]"><div className="flex items-start justify-between"><div><span className="text-[0.7rem] text-[#9898ad]">Completion trend</span><h3 className="mt-[7px] text-base">Weekly output</h3></div><span className="text-[0.68rem] text-[#8b5cf6]">● Completed</span></div><ResponsiveContainer width="100%" height={220}><AreaChart data={trend}><defs><linearGradient id="completionFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8b5cf6" stopOpacity={.45} /><stop offset="100%" stopColor="#8b5cf6" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#ffffff1a" vertical={false} /><XAxis dataKey="day" stroke="#9898ad" fontSize={11} /><YAxis stroke="#9898ad" fontSize={11} allowDecimals={false} /><Tooltip /><Area type="monotone" dataKey="completed" stroke="#8b5cf6" fill="url(#completionFill)" strokeWidth={3} /></AreaChart></ResponsiveContainer></div><div className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 backdrop-blur-[14px]"><div><span className="text-[0.7rem] text-[#9898ad]">Workload</span><h3 className="mt-[7px] text-base">Tasks by status</h3></div><ResponsiveContainer width="100%" height={220}><BarChart data={statusData}><CartesianGrid stroke="#ffffff1a" vertical={false} /><XAxis dataKey="name" stroke="#9898ad" fontSize={10} /><YAxis stroke="#9898ad" fontSize={11} allowDecimals={false} /><Tooltip /><Bar dataKey="value" fill="#8b5cf6" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></div></section>;
}
